name: Metrics
on:
  # Schedule updates (each day at noon)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:

  achievements:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ellisonleao
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)

  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: header
          config_timezone: Australia/Sydney
  lines:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes

  acti_comm:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: activity, community
          config_timezone: Australia/Sydney

  iso_calender:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: ""
          config_timezone: Australia/Sydney
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  issue_pr_lang:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: ""
          config_timezone: Australia/Sydney
          plugin_followup: yes
          plugin_languages: yes


  repositories:
    runs-on: ubuntu-latest
    environment:
      name: PROFILE
    permissions:
      contents:  write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: repositories
          config_timezone: Australia/Sydney
