name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

concurrency:
  group: profile-metrics
  cancel-in-progress: false

jobs:
  header:
    runs-on: ubuntu-latest
    environment: PROFILE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: header
          config_timezone: Australia/Sydney

  repositories:
    runs-on: ubuntu-latest
    environment: PROFILE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: repositories
          config_timezone: Australia/Sydney

  activity-community:
    runs-on: ubuntu-latest
    environment: PROFILE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: acti_comm.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: activity, community
          config_timezone: Australia/Sydney

  isocalendar:
    runs-on: ubuntu-latest
    environment: PROFILE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso_calender.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: ""
          config_timezone: Australia/Sydney
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  followup-languages:
    runs-on: ubuntu-latest
    environment: PROFILE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: ""
          config_timezone: Australia/Sydney
          plugin_followup: yes
          plugin_languages: yes

  lines:
    runs-on: ubuntu-latest
    environment: PROFILE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: lines-of-code.svg
          token: ${{ secrets.METRIC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Isaac7777-cpu
          template: classic
          base: ""
          config_timezone: Australia/Sydney
          plugin_lines: yes
          plugin_lines_skipped: |
            Isaac7777-cpu/stat2001-summaries
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_lines_delay: 30
